export const GAME_CONFIG = {
  BALL_SIZE: 7,
  CANVAS_WIDTH: 150,
  CANVAS_HEIGHT: 150,
  INITIAL_COMPUTER_SPEED: 2,
  INITIAL_PLAYER_POS_X: 70,
  INITIAL_BALL_SPEED: 2,
  PADDLE_WIDTH: 24,
  PADDLE_HEIGHT: 2,
  CANVAS_OFFSET_X: 43,
  CANVAS_OFFSET_Y: 40
} as const;

export const COLORS = {
  BACKGROUND: '#111',
  CANVAS_BG: '#000000',
  LINE_WHITE: '#FFFFFF',
  TEXT_WHITE: '#B0B0B0'
} as const;

export const UI_CONFIG = {
  BUTTON_SIZE: 24,
  TEXT_SIZE: 14
} as const;

export const SCORE_CONFIG = {
  WIDTH: 30,
  HEIGHT: 60
} as const;

export const GAMEPLAY_CONFIG = {
  WIN_SCORE: 7,
  MAX_BALL_SPEED_MULTIPLIER: 2,
  BALL_SPEED_INCREMENT: 0.15
} as const;

export const CONTROLS_CONFIG = {
  BUTTON_MARGIN_LEFT: 12,
  BUTTON_MARGIN_VERTICAL: 24
} as const;

export const SCORES_DISPLAY_CONFIG = {
  MARGIN_LEFT_PERCENT: '50%',
  MARGIN_TOP_PERCENT: '35%'
} as const;
